### ISSUE TITLE
DatePickerIOS is invisible having dark mode enabled

### ISSUE THREAD

**Issue by djinely** [CareLuLu/react-native-web-ui-components#226]
## Expected Behavior
DatePickerIOS is invisible having dark mode enabled.

## Current Behavior
<img width="430" alt="Screen Shot 2020-07-21 at 15 42 24" src="https://user-images.githubusercontent.com/11662157/88056169-cdeb2b00-cb68-11ea-970b-4ec0ade2f122.png">

## Possible Solution
background should be handled differently:
https://github.com/CareLuLu/react-native-web-ui-components/blob/831b58242ba266d54f81fe5b72020e964718fdb3/src/Datepicker/index.js#L42

## Steps to Reproduce (for bugs)
Activate dark mode and open the datepicker

see this reference: https://github.com/facebook/react-native/issues/26299

**Comment by CareLuLu-Gabriel** [comment]
@djinely I couldn't reproduce the problem. I tried both with an actual iPhone and the iPhone simulator. What version of the library are you using?

If the `package.json` of your version of `react-native-web-ui-components` has `"@react-native-community/datetimepicker": "^2.4.0", you shouldn't have a problem.
