### ISSUE TITLE
Debounce option for autocomplete input text

### ISSUE THREAD

**Issue by clkevinf19** [CareLuLu/react-native-web-ui-components#41]
## Expected Behavior

I should be able to set an option in `Autocomplete` component to add debounce option (in millisecond) so we can prevent `onChangeText` from being called repeatedly in short amount of time.

## Current Behavior

`Autocomplete` `onChangeText` event always fire when text is changed repeatedly in short amount of time.

## Possible Solution

Add `debounce` on update text event, similar to https://dev.to/gabe_ragland/debouncing-with-react-hooks-jci

## Context

This is helpful when you use async operation in `Autocomplete` component such as calling api to fetch data during `onChangeText` event and want to limit the operation when user stop typing for 500ms.

**Comment by CareLuLu-Gabriel** [comment]
Fixed by https://github.com/CareLuLu/react-native-web-ui-components/commit/f1b4e933cef71da01bb36abb56e19c13bf50a1bb
